include:
  - project: "platform/gitlab-ci"
    file: "/customer-frontends/workflow.yaml"

variables:
  SERVICE_NAME: customer-frontends/slotsbet

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      when: always
      variables:
        IMAGE_TAG: $CI_COMMIT_BRANCH

    - if: $CI_COMMIT_BRANCH == "dev"
      when: always
      variables:
        IMAGE_TAG: $CI_COMMIT_BRANCH

    - if: $CI_COMMIT_BRANCH =~ /tpbe-\d+/i
      when: always
      variables:
        IS_TASK_BRANCH: "1"

    - when: never
