image: 038978826977.dkr.ecr.eu-central-1.amazonaws.com/infrastructure/gitlab-builder:latest

services:
  - name: docker:dind
    alias: docker
    command: [ "--tls=false" ]

variables:
  SERVICE_NAME: customer-frontends/slotsbet
  DOCKER_TLS_CERTDIR: ""

stages:
  - build

"Build docker image":
  stage: build
  only:
    - dev
    - main
  before_script:
    - aws ecr get-login-password | docker login --username AWS --password-stdin $ECR_REGISTRY
  script:
    - aws ecr describe-repositories --repository-names $SERVICE_NAME || aws ecr create-repository --repository-name $SERVICE_NAME
    - docker build -t $ECR_REGISTRY/$SERVICE_NAME:$CI_COMMIT_BRANCH-$CI_COMMIT_SHORT_SHA --build-arg NPM_TOKEN=$CI_JOB_TOKEN .
    - docker push $ECR_REGISTRY/$SERVICE_NAME:$CI_COMMIT_BRANCH-$CI_COMMIT_SHORT_SHA
