export interface ProfileInterface {
  address: string|null,
  agreedTc: string|null,
  birthPlace: string|null,
  birthdate: string|null,
  confirmedAt: string|null,
  country: string|null,
  createdAt: string,
  currency: string|null,
  email: string|null,
  firstName: string|null,
  gender: string|null,
  id: string,
  lastName: string|null,
  nationality: string|null,
  nickname: string|null,
  phone: string|null,
  profession: string|null,
  receiveEmail: boolean|null,
  receiveSms: boolean|null,
  status: number,
  timeZone: string|null
}
