export default defineEventHandler(() => ({
  // You have props "param", "min", "max"
  // You need to wrap your prop to {}, like {param}
  // param - params of validation rule
  // min - first value of params if param has different values
  // max - second value of params if param has different values

  countryCode: 'The country code format is invalid',
  languageCode: 'The language code format is invalid',
  minAge: 'Age must be {param} years old or above',
  maxAge: 'Age must be {param} years old or less',
  phone: 'The phone format is invalid',
  lowercase: 'The field value must be lowercase',
  uppercase: 'The field value must be uppercase',
  accepted: 'Field must be accepted',
  declined: 'Field must be declined',
  before: 'The field value must be a date before {param}',
  before_or_equal: 'The field value must be a date before or equal to {param}',
  after: 'The field value must be a date after {param}',
  after_or_equal: 'The field value must be a date after or equal to {param}',
  alpha: 'The field value must only contain letters',
  alpha_dash: 'The field value must only contain letters, numbers, dashes and underscores',
  alpha_num: 'The field value must only contain letters and numbers',
  array: 'The field value must be an array',
  boolean: 'The field value must be true or false',
  confirmed: 'Doesn\'t match the New password',
  date: 'The field value is not a valid date',
  date_equals: 'The field value must be a date equal to {param}',
  different: 'The field value and {param} value must be different',
  digits: 'The field value must be {param} digits',
  digits_between: 'The field value must be between {min} and {max} digits',
  email: 'The field value must be a valid email address',
  ip: 'The field value must be a valid IP address',
  mac_address: 'The field value must be a valid MAC address',
  max: 'The field value must not be greater than {param}',
  min: 'The field value must be at least {param}',
  numeric: 'The field value must be a number',
  regex: 'The field value format is invalid',
  not_regex: 'The field value format is invalid',
  required: 'This field is required',
  required_if: 'This field is required when {param} has value',
  string: 'The field value must be a string',
  url: 'The field value must be a valid URL',
  login: 'The data is incorrect. Please check the data and try again',
}));
