backend:
  repo: platform/customer-frontends/slotsbet
  branch: dev
__link-label: &linkLabel
  name: label
  label: Label
  widget: string
__link-url: &linkUrl
  name: url
  label: Url
  widget: string
__locale-field: &localeField
  name: locale
  label: Locale (settings)
  widget: string
__link-variable: &linkArray
  - *linkLabel
  - *linkUrl
__project-icon: &projectIcon
  name: icon
  label: Icon
  widget: select
  options: ['cherry', 'sport', 'slots', 'live-casino', 'table-games', 'turbo-games', 'sport-book', 'tfs-token',
            'bonuses', 'live-support', 'vip', 'tournament', 'lottery', 'quest', 'shop', 'heart', 'history', 'wallet',
            'bonus', 'user', 'log-out']
collections:
  - name: validationMessages
    label: Validation Messages
    create: true
    identifier_field: locale
    extension: json
    format: json
    folder: content/validations
    editor:
      preview: false
    fields:
      - name: locale
        label: Locale (settings)
        widget: string
        hint: Rules will be use for LOCALE. You have props "param", "min", "max".
          You need to wrap your prop to {}, like {param}. param - params of validation rule;
      - name: countryCode
        label: Country Code
        widget: string
      - name: languageCode
        label: Language Code
        widget: string
      - name: minAge
        label: Min Age
        widget: string
      - name: maxAge
        label: Max Age
        widget: string
      - name: phone
        label: Phone
        widget: string
      - name: lowercase
        label: Lowercase
        widget: string
      - name: uppercase
        label: Uppercase
        widget: string
      - name: accepted
        label: Accepted
        widget: string
      - name: declined
        label: Declined
        widget: string
      - name: before
        label: Before (date)
        widget: string
      - name: before_or_equal
        label: Before or Equal (date)
        widget: string
      - name: after
        label: After (date)
        widget: string
      - name: after_or_equal
        label: After or Equal (date)
        widget: string
      - name: alpha
        label: Alpha
        widget: string
      - name: alpha_dash
        label: Alpha Dash
        widget: string
      - name: alpha_num
        label: Alpha Num
        widget: string
      - name: array
        label: Array
        widget: string
      - name: boolean
        label: Boolean
        widget: string
      - name: confirmed
        label: Confirmed
        widget: string
      - name: date
        label: Date
        widget: string
      - name: date_equals
        label: Date Equals
        widget: string
      - name: different
        label: Defferent
        widget: string
      - name: digits
        label: Digits
        widget: string
      - name: digits_between
        label: Digits Between
        widget: string
      - name: email
        label: Email
        widget: string
      - name: ip
        label: IP
        widget: string
      - name: mac_address
        label: Mac Address
        widget: string
      - name: max
        label: Max
        widget: string
      - name: min
        label: Min
        widget: string
      - name: numeric
        label: Numeric
        widget: string
      - name: regex
        label: Regex
        widget: string
      - name: not_regex
        label: Not Regex
        widget: string
      - name: required
        label: Required
        widget: string
      - name: required_if
        label: Required If
        widget: string
      - name: string
        label: String
        widget: string
      - name: url
        label: Url
        widget: string
      - name: login
        label: Login (invalid data error)
        widget: string

  - name: fields
    label: Fields
    create: true
    identifier_field: locale
    extension: json
    format: json
    folder: content/fields
    __fields-array: &fieldsArray
      - name: label
        label: Label
        widget: string
      - name: placeholder
        label: Placeholder
        widget: string
        required: false
    editor:
      preview: false
    fields:
      - *localeField
      - name: password
        label: Password
        widget: object
        fields: *fieldsArray
      - name: currentPassword
        label: Current Password
        widget: object
        fields: *fieldsArray
      - name: newPassword
        label: New Password
        widget: object
        fields: *fieldsArray
      - name: repeatNewPassword
        label: Repeat New Password
        widget: object
        fields: *fieldsArray
      - name: firstName
        label: First Name
        widget: object
        fields: *fieldsArray
      - name: lastName
        label: Last Name
        widget: object
        fields: *fieldsArray
      - name: nationality
        label: Nationality
        widget: object
        fields: *fieldsArray
      - name: nickname
        label: Nickname
        widget: object
        fields: *fieldsArray
      - name: gender
        label: Gender
        widget: object
        fields: *fieldsArray
      - name: city
        label: City
        widget: object
        fields: *fieldsArray
      - name: address
        label: Address
        widget: object
        fields: *fieldsArray
      - name: additionalAddress
        label: Additional Address
        widget: object
        fields: *fieldsArray
      - name: postalCode
        label: Postal Code
        widget: object
        fields: *fieldsArray
      - name: timeZone
        label: Time Zone
        widget: object
        fields: *fieldsArray
      - name: profession
        label: Profession
        widget: object
        fields: *fieldsArray
      - name: language
        label: Language
        widget: object
        fields: *fieldsArray
      - name: bonusCode
        label: Bonus Code
        widget: object
        fields: *fieldsArray
      - name: securityQuestion
        label: Security Question
        widget: object
        fields: *fieldsArray
      - name: securityAnswer
        label: Security Answer
        widget: object
        fields: *fieldsArray
      - name: email
        label: Email
        widget: object
        fields: *fieldsArray
      - name: country
        label: Country
        widget: object
        fields: *fieldsArray
      - name: currency
        label: Currency
        widget: object
        fields: *fieldsArray
      - name: agreements
        label: Agreements
        widget: object
        fields: *fieldsArray
      - name: receiveEmailPromo
        label: Receive Email Promo
        widget: object
        fields: *fieldsArray
      - name: receiveSmsPromo
        label: Receive Sms Promo
        widget: object
        fields: *fieldsArray
      - name: phone
        label: Phone
        widget: object
        fields: *fieldsArray
      - name: birthdate
        label: Birthdate
        widget: object
        fields: *fieldsArray
      - name: placeOfBirth
        label: Place of Birth
        widget: object
        fields: *fieldsArray
      - name: personalIdNumber
        label: Personal Id Number
        widget: object
        fields: *fieldsArray
      - name: message
        label: Message
        widget: object
        fields: *fieldsArray

  - name: mainLayout
    label: Main Layout
    create: true
    identifier_field: locale
    extension: json
    format: json
    folder: content/main-layout
    editor:
      preview: false
    fields:
      - *localeField
      - name: header
        label: Header
        widget: object
        fields:
          - name: loginButton
            label: Login Button
            widget: string
          - name: registrationButton
            label: Registration Button
            widget: string
          - name: search
            label: search
            widget: object
            fields:
              - name: placeholder
                label: Placeholder
                widget: string
              - name: moreButton
                label: More Button
                widget: string
              - name: emptyLabel
                label: Empty Label
                widget: string
              - name: emptyText
                label: Empty Text
                widget: string
              - name: tryLabel
                label: Try Label
                widget: string
          - name: depositButton
            label: Deposit Button
            widget: string

      - name: userNavigation
        label: User Navigation
        widget: object
        fields:
          - name: profileLinks
            label: Profile Links
            label_singular: link
            widget: list
            fields:
              - *linkLabel
              - *linkUrl
              - *projectIcon
          - name: logoutButton
            label: Logout Button
            widget: string

      - name: siteSidebar
        label: Site Sidebar
        widget: object
        __sidebar-block: &sidebarBlock
          - *linkLabel
          - name: url
            label: Url
            required: false
            widget: string
          - *projectIcon
          - name: items
            label: Items
            widget: list
            label_singular: link
            fields: *linkArray
        fields:
          - name: gamesToggler
            label: Game Toggler
            widget: list
            min: 2
            max: 2
            fields:
              - *linkLabel
              - *linkUrl
              - *projectIcon
          - name: profileMenu
            label: Profile Menu
            widget: object
            fields:
              - name: levelLabel
                label: Level Label
                widget: string
              - name: depositButton
                label: Deposit  Button
                widget: string
              - name: profileButton
                label: Profile Button
                widget: object
                fields: *linkArray
          - name: topMenu
            label: Top Menu
            widget: list
            label_singular: item
            fields:
              - *linkLabel
              - *linkUrl
              - *projectIcon
              - name: gameList
                label: Game List
                widget: list
                label_singular: game identity
                field: {name: gameIdentity, label: Game Identity, widget: string}
          - name: tokenMenu
            label: Token Menu
            widget: list
            label_singular: item
            fields: *sidebarBlock
          - name: bonusesMenu
            label: Bonuses Menu
            widget: list
            label_singular: item
            fields: *sidebarBlock
          - name: userMenu
            label: User Menu
            widget: list
            label_singular: item
            fields: *sidebarBlock
          - name: bottomMenu
            label: Bottom Menu
            widget: list
            label_singular: item
            fields: *sidebarBlock
          - name: sidebarFooterMenu
            label: Sidebar Footer Menu
            widget: list
            label_singular: link
            fields: *linkArray

      - name: footer
        label: Footer
        widget: object
        __group-list: &groupList
          - name: title
            label: Title
            widget: string
          - name: items
            label: Links
            widget: list
            fields: *linkArray
        fields:
          - name: promoMenu
            label: Promo Menu
            widget: object
            fields: *groupList
          - name: infoMenu
            label: Info Menu
            widget: object
            fields: *groupList
          - name: helpMenu
            label: Help Menu
            widget: object
            fields: *groupList
          - name: responsibilityLabel
            label: Responsibility Label
            widget: string
          - name: copyright
            label: Copyright
            widget: string

      - name: mobileMenu
        label: Mobile Menu
        widget: object
        fields:
          - name: menuLabel
            label: Menu Label
            widget: string
          - name: items
            label: Menu Links
            widget: list
            min: 3
            max: 3
            fields:
              - *linkLabel
              - *linkUrl
              - *projectIcon

      - name: cookiePopup
        label: Cookie Popup
        widget: object
        fields:
          - name: text
            label: Text
            widget: markdown
          - name: acceptButton
            label: Accept Button
            widget: string

  - name: mainSlider
    label: Main Slider
    create: true
    identifier_field: locale
    extension: json
    format: json
    folder: content/main-slider
    editor:
      preview: false
    fields:
      - *localeField
      - name: slider
        label: Slider
        widget: list
        label_singular: slide
        summary: '{{fields.title}}'
        fields:
          - name: slideStatus
            label: Slide Status
            widget: select
            options: ['Published', 'Hide']
          - name: title
            label: Slide Title
            widget: markdown
          - name: content
            label: Slide Content
            widget: markdown
            required: false
          - name: button
            label: Slide Button
            widget: object
            required: false
            fields:
              - *linkLabel
              - name: url
                label: Url
                widget: string
                required: false
          - name: images
            label: Images
            widget: object
            fields:
              - name: mobile
                label: Mobile Layout
                widget: object
                fields:
                  - name: backgroundImage
                    label: Background Image
                    widget: image
                    allow_multiple: false
                  - name: faceImage
                    label: Face Image
                    widget: image
                    asslow_multiple: false
              - name: desktop
                label: Desktop Layout
                widget: object
                fields:
                  - name: backgroundImage
                    label: Background Image
                    widget: image
                    allow_multiple: false
                  - name: faceImage
                    label: Face Image
                    widget: image
                    asslow_multiple: false

  - name: popups
    label: Site Popups
    create: true
    identifier_field: locale
    extension: json
    format: json
    folder: content/popups
    editor:
      preview: false
    fields:
      - *localeField
      - name: login
        label: Login Popup
        widget: object
        fields:
          - name: title
            label: Title
            widget: string
          - name: loginButton
            label: Login Button Label
            widget: string
          - name: forgotButton
            label: Forgot Button Label
            widget: string
            hint: Put text inside "*" to highlight it (*test*)
          - name: registrationButton
            label: Registration Button Label
            widget: string
            hint: Put text inside "*" to highlight it (*test*)
      - name: forgot
        label: Forgot Password Popup
        widget: object
        fields:
          - name: title
            label: Title
            widget: string
          - name: description
            label: Description
            widget: string
            required: false
          - name: forgotButton
            label: Forgot Button Label
            widget: string
          - name: registrationButton
            label: Registration Button Label
            widget: string
            hint: Put text inside "*" to highlight it (*test*)



